#!/usr/bin/env python3
"""Derive ``local/backchannel_lexicon.txt`` from Ekstedt's Switchboard
backchannel annotations (``dataset_swb/backchannels.csv`` in
https://github.com/ErikEkstedt/VoiceActivityProjection), the file the
Talking Turns paper cites for its backchannel phrase set (A.4).

    python local/make_backchannel_lexicon.py /path/to/backchannels.csv \
        [--min_count 100] [--max_words 2] [--out local/backchannel_lexicon.txt]

The list is committed so the metric never depends on the csv at run time;
re-run this script only to change the cutoff, and say so in the header.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from egs3.conversational.tts.src.metrics.backchannel_lexicon import (  # noqa: E402
    DEFAULT_MAX_WORDS,
    DEFAULT_MIN_COUNT,
    build_lexicon,
    write_lexicon,
)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--min_count", type=int, default=DEFAULT_MIN_COUNT)
    ap.add_argument("--max_words", type=int, default=DEFAULT_MAX_WORDS)
    ap.add_argument(
        "--out", default=str(Path(__file__).resolve().parent / "backchannel_lexicon.txt")
    )
    a = ap.parse_args()
    entries = build_lexicon(Path(a.csv), a.min_count, a.max_words)
    total = sum(c for _, c in entries)
    header = (
        "Switchboard backchannel phrases (Ekstedt backchannels.csv, words column),\n"
        f"normalised, <= {a.max_words} words, count >= {a.min_count}: "
        f"{len(entries)} phrases, {total} annotated backchannels covered.\n"
        "Generated by local/make_backchannel_lexicon.py; phrase<TAB>count."
    )
    write_lexicon(entries, Path(a.out), header)
    print(f"wrote {a.out}: {len(entries)} phrases, {total} backchannels covered")


if __name__ == "__main__":
    main()
