<script setup>
import { ref, computed } from 'vue'

const env      = ref('local')
const workers  = ref(4)
const queue    = ref('gpu')
const account  = ref('myproject')
const cores    = ref(4)
const memory   = ref('32GB')
const walltime = ref('02:00:00')
const processes = ref(1)
const localdir  = ref('/scratch/$USER/$SLURM_JOB_ID')

const yamlOutput = computed(() => {
  if (env.value === 'local') {
    return `parallel:\n  env: local\n  n_workers: ${workers.value}\n  options: {}`
  }
  if (env.value === 'local_gpu') {
    return `parallel:\n  env: local_gpu\n  n_workers: ${workers.value}\n  options: {}`
  }
  return (
    `parallel:\n  env: slurm\n  n_workers: ${workers.value}\n  options:\n` +
    `    queue: ${queue.value}\n    account: ${account.value}\n` +
    `    cores: ${cores.value}\n    memory: "${memory.value}"\n` +
    `    walltime: "${walltime.value}"\n    processes: ${processes.value}\n` +
    `    local_directory: "${localdir.value}"`
  )
})

const sbatchLines = computed(() => {
  const cpuPerTask = Math.ceil(cores.value / processes.value)
  return [
    { type: 'shebang', text: '#!/bin/bash' },
    { type: 'directive', flag: '#SBATCH', opt: '-p', val: queue.value },
    { type: 'directive', flag: '#SBATCH', opt: '-A', val: account.value },
    { type: 'directive', flag: '#SBATCH', opt: '--ntasks', val: String(processes.value) },
    { type: 'directive', flag: '#SBATCH', opt: '--cpus-per-task', val: String(cpuPerTask) },
    { type: 'directive', flag: '#SBATCH', opt: '--mem', val: memory.value },
    { type: 'directive', flag: '#SBATCH', opt: '--time', val: walltime.value },
    { type: 'directive', flag: '#SBATCH', opt: '-J', val: 'dask-worker' },
    { type: 'comment', text: `# generated by dask_jobqueue — ${workers.value} jobs total` },
  ]
})
</script>

<template>
  <section class="guide-section" id="config-builder" style="border-bottom: none">
    <div class="container">
      <p class="section-num">05 / config builder</p>
      <h2 class="section-h2">Config builder</h2>
      <p class="section-desc">
        Select an execution environment and fill in the values. The YAML config and the generated
        SLURM script update in real time.
      </p>

      <div class="config-grid">
        <!-- Controls -->
        <div class="config-controls">
          <div class="config-section-label">Execution environment</div>

          <div class="config-field">
            <label class="config-label">env <span>execution mode</span></label>
            <select v-model="env">
              <option value="local">local — same process (dev / debug)</option>
              <option value="local_gpu">local_gpu — multiple GPUs on one machine</option>
              <option value="slurm">slurm — SLURM cluster</option>
            </select>
          </div>

          <div class="config-field">
            <label class="config-label">n_workers <span>number of workers (SLURM: job count)</span></label>
            <input type="number" v-model.number="workers" min="1" max="128" />
          </div>

          <!-- SLURM fields -->
          <template v-if="env === 'slurm'">
            <div class="config-divider" />
            <div class="config-section-label">SLURM options (options:)</div>
            <div class="slurm-grid">
              <div class="config-field">
                <label class="config-label">queue</label>
                <input type="text" v-model="queue" />
              </div>
              <div class="config-field">
                <label class="config-label">account</label>
                <input type="text" v-model="account" />
              </div>
              <div class="config-field">
                <label class="config-label">cores <span>per job</span></label>
                <input type="number" v-model.number="cores" min="1" max="128" />
              </div>
              <div class="config-field">
                <label class="config-label">memory <span>per job</span></label>
                <input type="text" v-model="memory" />
              </div>
              <div class="config-field">
                <label class="config-label">walltime</label>
                <input type="text" v-model="walltime" />
              </div>
              <div class="config-field">
                <label class="config-label">processes <span>per job</span></label>
                <input type="number" v-model.number="processes" min="1" max="32" />
              </div>
            </div>
            <div class="config-field">
              <label class="config-label">local_directory <span>temp files</span></label>
              <input type="text" v-model="localdir" />
            </div>

            <div class="config-divider" />
            <div class="config-section-label">Generated #SBATCH script (preview)</div>
            <div class="sbatch-preview">
              <div class="sbatch-title">Auto-generated #SBATCH script (1 job)</div>
              <template v-for="(line, i) in sbatchLines" :key="i">
                <template v-if="line.type === 'shebang'">
                  <span class="sbatch-dir">{{ line.text }}</span>{{ '\n' }}
                </template>
                <template v-else-if="line.type === 'directive'">
                  <span class="sbatch-dir">{{ line.flag }}</span>
                  {{ ' ' }}{{ line.opt }}
                  {{ ' ' }}<span class="sbatch-val">{{ line.val }}</span>{{ '\n' }}
                </template>
                <template v-else>
                  <span style="color: var(--text3)">{{ line.text }}</span>{{ '\n' }}
                </template>
              </template>
            </div>
          </template>

          <!-- local_gpu note -->
          <template v-if="env === 'local_gpu'">
            <div class="config-divider" />
            <div class="callout callout-info" style="margin: 0">
              <span class="callout-icon">ℹ</span>
              <div>
                <p>
                  <strong>Requirements for local_gpu:</strong> Install <code>dask_cuda</code>
                  (<code>pip install dask-cuda</code>). Set <code>n_workers</code> to at most
                  the number of available GPUs.
                </p>
              </div>
            </div>
          </template>
        </div>

        <!-- Output -->
        <div class="config-output">
          <div class="config-output-header">
            <span>parallel_config.yaml</span>
            <span style="color: var(--worker); font-size: 11px">● live</span>
          </div>
          <pre><code>{{ yamlOutput }}</code></pre>
        </div>
      </div>

      <div class="callout callout-info" style="margin-top: 2rem">
        <span class="callout-icon">ℹ</span>
        <div>
          <p>
            <strong>Other cluster types (PBS, SGE, LSF, HTCondor, ...):</strong>
            Change <code>env</code> to <code>"pbs"</code>, <code>"sge"</code>,
            <code>"lsf"</code>, or <code>"htcondor"</code>. The available <code>options</code>
            vary by scheduler — see the
            <a href="https://jobqueue.dask.org/en/latest/" target="_blank">dask-jobqueue documentation</a>.
          </p>
        </div>
      </div>
    </div>
  </section>
</template>
